version: '2'
services:
  api:
    container_name: api
    build: .
    ports: 
      - "8181:8181"
  sonar:
    container_name: sonarqube8
    image: sonarqube:8.4.1-community
    ports:
      - "7000:9000"
  #oracle:
    #image: "bofm/oracle12c"
    #restart: "unless-stopped"
    #ports:
        #- 1521:1521
        #- 5500:5500
    #volumes:
        #- ./setup-scripts:/opt/oracle/scripts/setup
        #- ./dump:/opt/oracle/dump
    #environment: 
        #- "ORACLE_USER=oracle"
        #- "ORACLE_PWD=oracle"
        #- "ORACLE_DATABASE=ORCL"
        #- "SOURCE_SCHEMA=ORCL"
