version: '2'
services:
  api:
    build: .
    ports: 
      - "8181:8181"
  #oracle:
    #image: "bofm/oracle12c"
    #restart: "unless-stopped"
    #ports:
        #- 1521:1521
        #- 5500:5500
    #volumes:
        #- ./setup-scripts:/opt/oracle/scripts/setup
        #- ./dump:/opt/oracle/dump
    #environment: 
        #- "ORACLE_USER=oracle"
        #- "ORACLE_PWD=oracle"
        #- "ORACLE_DATABASE=ORCL"
        #- "SOURCE_SCHEMA=ORCL"
