version: '3'
services:
  api:
    container_name: api
    build: .
    ports: 
      - "8181:8181"
  sonar:
    container_name: sonarqube8
    image: sonarqube:8.4.1-community
    ports:
      - "9000:9000"
  #oracle:
    #image: "bofm/oracle12c"
    #restart: "unless-stopped"
    #ports:
        #- 1521:1521
        #- 5500:5500
    #volumes:
        #- ./setup-scripts:/opt/oracle/scripts/setup
        #- ./dump:/opt/oracle/dump
    #environment: 
        #- "ORACLE_USER=oracle"
        #- "ORACLE_PWD=oracle"
        #- "ORACLE_DATABASE=ORCL"
        #- "SOURCE_SCHEMA=ORCL"
  jenkins:
    image: jenkins/jenkins
    ports:
      - '8282:8080'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/usr/bin/docker-compose:/usr/bin/docker-compose'
volumes:
  jenkins_home:
    driver: local
